### ISSUE TITLE
having standardised codebase for debond-App

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/Debond-App#11]
# Description :

only 2 branches (main and development ) for the stable release and the ongoing features 

PR's will be first added for the developing branch in order to add the work absed on the tasks , and then when epic is finished , its added to  the main contract .

**Comment by GrandGarcon** [comment]
ok then we are going for finally two branches 

new-main will be the final branch for this sprint . and the ERC3475-integration will be renamed to the development branch for the tasks in the current sprint.

**Comment by dr-chain** [comment]
@GrandGarcon ok thank you for the clarification

**Comment by dr-chain** [comment]
I saw now there are only two branches. I am closing the issue @GrandGarcon
