### ISSUE TITLE
Task:  Function for staking DBGT bond to get Vote token

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/Debond-App#2]
# Description

This function will be allow user  stake its issued DBGT token to issue Vote token , which is then used for voting in SigmaGovernance.  this requires first to fetch pair price and then doing swap via the Debond router.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

- [ ] there is   unit test for mocking  the debondRouter values
- [ ] we get the assertion test for the  conversions based on the router condirions

**Test Configuration**:
* solidity mock contracts  
* hardhat package

# Checklist:

- [x] define  vars to store the token balance of vote token
- [x]   fetch getBondExchangeRateDBGTtoDBIT() for  getting the pair exchange rate for token
- [x]   verify the logic from Yu or samuel how to restructure.
- [ ]  add additional mock functions for the tests  and then document them for other team

**Comment by dr-chain** [comment]
@GrandGarcon please tag the reviewer

**Comment by GrandGarcon** [comment]
@sgmfinance  and @drikssy , the function buyVoteTokenWithDBGT in debondBank needs review.

**Comment by GrandGarcon** [comment]
feedback by @sgmfinance :  we will only have Vote as the bond , with its own class , but they will be generated as an interest DBIT for everytime you stake your DBGT for the vote . and after the proposal  is completed , you have the possiblity to retrieve the DBGT bonds with the interest in form of both DBIT and Vote bonds .

**Comment by dr-chain** [comment]
Moving back the task to product backlog, since not in priority for the demo (scheduled for end of April?)

**Comment by GrandGarcon** [comment]
the mechanism has changed , now we only have dGOV token for the governance
