### ISSUE TITLE
Task: Refactoring the currrent sigmoid bonds.

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/Debond-App#4]
# Description

Current version of SigmoidBonds is very much outdated based on the current specifications of EIP standard and incompatible on how we can couple the interfaces of the bond with the enhancements in the sigmoidBonds . 

some of the features that we need to  insure are : 

- currently the maturity time of the bond is converted into the fixRate and maturity rate for finding the exit conditions of the bonds.
     - also fixRate has  single redemption condition (as explained in the Testimate(n) on page 7 of paper v2 version).
     -  redemption conditions  will be referred from core of the APM
     -  bank Contract along with current  Router.sol will be the combined interface for fetching these details by the bond in order to find the redeeming condition. 
     - currently bond can only be issued by the  APM (but then can be fixed later via the proposal contract for next  version of the contract).
     - it has to handle the  cases of bond transfer and redeeming

## Type of change

Please delete options that are not relevant.

- [x] Refactoring 
- [ ] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# How Has This Been Tested?
it will be tested  by  
- [ ]  unit tests for testing each of the assertion functions for populated nonce and maturity data. 
- [ ] integration tests with actual deployment of the scenarios of redeeming  mature  bonds

**Test Configuration**:
* solidity remix / hardhat / gnosis mock library

# Checklist:

- [ ] implement with the clean interface. 
- [ ] review to be assigned to Yu for the verification 
- [ ]  implement the functions  and review  within assignes with comments
- [ ]  and then fullfill the unit tests 
- [ ]  try to moick the router / apm details if already not build completely

**Comment by dr-chain** [comment]
@drikssy @GrandGarcon  can you link the final version of the file to the issue?
I will have review it then.
