### ISSUE TITLE
Task: Refactor ISigmaGovernance

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/Debond-App#5]
# Description

Adding functions for
-  interfacing with router contracts for allowing  the user who has bought the vote tokens based on the 
-  invoking proposal  by the governance  .

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [ ] review by the team and committing the changes

**Test Configuration**:
sol

# Checklist:

- [x] write the specific function signature based on the understanding from the paper 
- [x] and then commit after being reviewed and thoroughly commented.

**Comment by GrandGarcon** [comment]
@drikssy  , @Edoumou  , @toufic0710   @yuliu-debond  could you refer the recent commit and tell whether other function signatures are needed ? thanks

**Comment by dr-chain** [comment]
@GrandGarcon Could you please link the file from the right branch to this issue? I will have a look at it.

**Comment by dr-chain** [comment]
@GrandGarcon If the work is not finalized, please move the issue to "In Progress" or "Sprint Backlog" or "Product Backlog" depending on the priority.

**Comment by GrandGarcon** [comment]
took review from @yuliu-debond  ,also tagging @drikssy  and @dr-chain  for technical review.

**Comment by dr-chain** [comment]
@GrandGarcon ok for me. closing the issue.
