### ISSUE TITLE
Task: create mock environment for sigmoid bond functionnal tests

### ISSUE THREAD

**Issue by drikssy** [Debond-Protocol/Debond-App#6]
# Description
Mock class details and nonce information for testing the sigmoidBonds

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Mock functional tests 
- [ ] Review

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] Bond is issued for arbitrary data 
- [ ] test is commented based on the 
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

**Comment by dr-chain** [comment]
Included in the demo. Closing this.
