### ISSUE TITLE
SigmoidBank.ListToken(...) function  bug. 

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/Debond-App#9]
**Describe the bug**
as checked by @dr-chain  , currently the function for ListToken doesnt have the check  for storing the list pairs corresponding to the given bond, so the line 

` list[_coinIndex].tokenAddress.push(_token);
`
will be executed by any value of bondIndex , **but within the same _bondIndex** . thus we need to maintain the 2D array for storing the tokenList mapping , and return the coinIndex where the token is added.

**Comment by GrandGarcon** [comment]
@dr-chain  and @Edoumou  for referral.

**Comment by GrandGarcon** [comment]
@dr-chain , the current implementation is [here](https://github.com/Debond-Protocol/Debond-App/blob/new-main/contracts/SigmoidBank.sol#L190). so in case if  there needs to be test for the implementation , i will have to add  this ticket to another epic of sigmoidBank tests , or you can check the implementation & then suggest the changes so that this issue is completed.

**Comment by dr-chain** [comment]
@GrandGarcon changed with new code. Bug solved, please test.

**Comment by dr-chain** [comment]
@GrandGarcon if this is tested, can we close the issue?

**Comment by dr-chain** [comment]
@GrandGarcon Please refer the new code being used in the bank contract.

**Comment by GrandGarcon** [comment]
here https://github.com/Debond-Protocol/Debond-v0/blob/development/contracts/DebondData.sol#L100 for whitelisting .
